### ISSUE TITLE
Add Assertion and Exception-throwing Guards

### ISSUE THREAD

**Issue by rossyman** [rossyman/taxiservice#2]
Add assertion and exception-throwing consistency guards within:
- TaxiCompany
- Passenger
- Vehicle
- Any other class that has potential for exception.

**Comment by rossyman** [comment]
When you open up a PR, make sure you reference this issue so it can automatically be moved to `Done` on the project board @Tristan-Nunn

**Comment by Tristan-Nunn** [comment]
PR merged
